# Generated by Django 4.1.4 on 2023-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses_app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='secation',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
