# Generated by Django 4.1.4 on 2023-02-18 19:56

from django.db import migrations, models
import online_courses_app_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses_app_api', '0002_course_duration_course_price_secation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Main_Image',
            field=models.ImageField(null=True, upload_to=online_courses_app_api.models.Course_Files),
        ),
    ]
